export const setup = {
  name: "TiemHommie",
  border: "#FF9B9B",
  inside: "#cf5b5b",
  color: "white",
  banner: "/assets/images/banner.jpg",
  error: "rgb(211, 47, 47)",
  success: "rgb(46, 125, 50)",
  email: "cskg.tiemhommie@gmail.com",
  backgroundColor: "#F6F9FC",
};
export const categoryList = [
  {
    categoryId: 1,
    categoryName: "Đồ chơi",
  },
  {
    categoryId: 2,
    categoryName: "Đồ nhồi bông",
  },
  {
    categoryId: 3,
    categoryName: "Trang sức",
  },
  {
    categoryId: 4,
    categoryName: "Đồ trang trí",
  },
];
export const productStatus = [
  { name: "Bán chạy", value: "bán chạy" },
  { name: "Hàng mới", value: "hàng mới" },
];
export const suggest = [
  "LEGO Hoa Hồng",
  "LEGO Hoa Hướng Dương",
  "LEGO Hoa Thủy Tiên",
  "LEGO Hoa Lan",
  "LEGO Hoa Tuilip",
  "LEGO Chậu Hoa Phát Tài",
  "LEGO Bình Hoa",
  "Tranh tô màu Kim Tự Tháp",
  "Tranh tô màu Vạn Lý Trường Thành",
  "Tranh tô màu Nhà hát Sydney",
  "Tranh tô màu Đồng hồ Big Ben",
  "Tranh tô màu Bình Minh",
  "Tranh tô màu núi Phú Sĩ",
  "Thú nhồi bông Cừu trắng",
  "Thú nhồi bông Thỏ dâu",
  "Thú nhồi bông Mèo nghiêng đầu",
  "Thú nhồi bông Cáo cam",
  "Thú nhồi bông Cánh cụt",
  "Gối nhồi bông chữ U khủng long",
  "Gối nhồi bông chữ U tai thỏ hồng",
  "Gối nhồi bông chữ U tai mèo",
  "Gối nhồi bông chữ U hoa văn caro",
  "Combo 4 huy hiệu cài áo Vô diện",
  "Huy hiệu cài áo Khủng long",
  "Huy hiệu cài áo Dơi tím",
  "Huy hiệu cài áo Ong & Hoa",
  "Huy hiệu cài áo Sách và Hoa",
  "Lắc tay bạc Tinh tú",
  "Lắc tay bạc Cườm Màu Thạch Lựu",
  "Lắc tay bạc Đơn giản",
  "Lắc tay bạc Dream Catcher",
  "Lắc tay bạc Hình chân mèo",
  "Dây chuyền bạc Aurora hình mèo",
  "Dây chuyền bạc Pha lê xanh dương",
  "Dây chuyền bạc Pha lê tím",
  "Dây chuyền bạc Pha lê xanh lục",
  "Dây chuyền bạc Pha lê hồng",
  "Chuông gió Vô diện",
  "Chuông gió Khủng Long Xanh lá",
  "Chuông gió Khủng Long Hồng",
  "Chuông gió Khủng Long Xanh dương nhạt",
  "Nến thơm Quả Táo",
  "Nến thơm Trái Cam",
  "Nến thơm Quả Đào",
  "Nến thơm Bánh Gato Dâu",
  "Nến thơm Xương Rồng",
  "Combo 4 tượng trang trí Hổ Con",
  "Tượng trang trí Mèo vuốt mặt",
  "Tượng trang trí Mèo ôm đầu",
  "Tượng trang trí Totoro",
];
export const priceList = [
  {
    id: 0,
    name: "< 50,000",
  },
  {
    id: 1,
    name: "50,000 - 200,000",
  },
  {
    id: 2,
    name: "200,000 - 500,000",
  },
  {
    id: 3,
    name: "500,000 - 800,000",
  },
];
